name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install protobuf-compiler
      run: sudo apt-get install protobuf-compiler
    - name: Check version of protoc
      run: protoc --version
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
